  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: springcloud2019-config-clqv-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: springcloud2019-config-clqvtest
#  请保存为UTF-8格式